### PR TITLE
Fix RTL

### LINKED ISSUE #158: [Bug] Block Component text obscured in RTL Languages
**Describe the bug**
Using Post and Page Builder while WordPress is set to use a locale with a right-to-left language, the **Add Block Component** interface's controls and text are obscured by the menu options that normally appear on the left of the panel.

**To Reproduce**
1. Install WordPress with Post and Page Builder
2. Navigate to **Settings > General** and select an RTL Language, such as Hebrew
3. Edit a page and select the **Add Block Component (+)** icon

**Expected behavior**
Controls should be usable and legible in RTL Languages

**Screenshots**
RTL-issues

**Additional context**
This issue was reported in the [BoldGrid User Forums](https://www.boldgrid.com/support/question/rtl-issues-with-builder/)

### PR DESCRIPTION
**Pull request by jamesros161**
Resolves #158 

### Testing Instructions ###

1. Install WordPress with Post and Page Builder using the following link: 
[post-and-page-builder.zip](https://github.com/BoldGrid/post-and-page-builder/files/9758664/post-and-page-builder.zip)

2. Navigate to Settings > General and select an RTL Language, such as Hebrew
3. Edit a page and select the Add Block Component (+) icon
4. Customize an added component.
5. Ensure the customize navigation is not blocking the text / controls.

### CODE REVIEW

**Review by avonville — APPROVED** [review]

**Comment by nicolepaschen** [comment]
panels have overlapping elements:
image

**Comment by nicolepaschen** [comment]
cannot check responsive utilities: 
image

**Comment by nicolepaschen** [comment]
background section buttons are overlapping each other 
image

**Comment by nicolepaschen** [comment]
image
tooltips appear on top of text in color picker for backgrounds

**Comment by nicolepaschen** [comment]
icon panel looks weird
image

**Pull request merged**
